name: Build

on:
  push

jobs:
  build_linux:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v3

      - name: Compile
        run: gcc -o img img.c -lm

      - name: Package (Linux)
        uses: actions/upload-artifact@v3
        with:
          name: Bundle
          path:
            img
  

  build_mac:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Compile
        run: clang -o img.cursed img.c -lm

      - name: Package (Mac)
        uses: actions/upload-artifact@v3
        with:
          name: Bundle
          path:
            img.cursed


  build_win:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Compile
        run: clang -o img.exe img.c

      - name: Package (Windows)
        uses: actions/upload-artifact@v3
        with:
          name: Bundle
          path:
            img.exe
  
  build_bundle:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Package
        uses: actions/upload-artifact@v3
        with:
          name: Bundle
          path: |
            init.lua
            qoi.lua
            LICENSE
