name: Build

on:
  push

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v3

      - name: Compile
        run: gcc -o img.com img.c -lm

      - name: Package (Linux)
        uses: actions/upload-artifact@v3
        with:
          name: Linux bundle
          path: |
            img.com
            init.lua
            qoi.lua
            LICENSE


  build_ape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download and compile
        run: |
          wget "https://justine.lol/cosmopolitan/cosmopolitan.zip"
          unzip cosmopolitan.zip
          gcc -g -Os -static -fno-pie -no-pie -nostdlib -nostdinc \
            -fno-omit-frame-pointer -pg -mnop-mcount \
            -o img.com.dbg img.c -Wl,--gc-sections -fuse-ld=bfd \
            -Wl,-T,ape.lds -include cosmopolitan.h crt.o ape.o cosmopolitan.a
          objcopy -S -O binary img.com.dbg img.com
      - name: Package APE
        uses: actions/upload-artifact@v3
        with:
          name: Universal bundle
          path: |
            img.com
            init.lua
            qoi.lua
            LICENSE
